### ISSUE TITLE
Distorted thumbnails on the homepage

### ISSUE THREAD

**Issue by Paaikan** [AlsaceDigitale/strasbourgstartups#15]
![thumbnails](https://cloud.githubusercontent.com/assets/24415288/20933937/d8b3a438-bbd9-11e6-81fc-da4b2e3f584e.png)

**Comment by Paaikan** [comment]
![thumbnails](https://cloud.githubusercontent.com/assets/24415288/20933921/cc513b74-bbd9-11e6-9042-19eee4f19cb7.png)

**Comment by yannski** [comment]
Fixed with https://github.com/AlsaceDigitale/strasbourgstartups/commit/c3b716a71ba26cee7ab70ec2fa0695dbc9da4207
